---

- set_fact:
    boottidal_hs: "/home/{{ansible_env.SUDO_USER}}/.local/share/nvim/plugged/vim-tidal/Tidal.ghci"

- block:
  - name: create required neovim and Plug directories
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
    with_items:
      - "/home/{{ansible_env.SUDO_USER}}/.config/nvim"
      - "/home/{{ansible_env.SUDO_USER}}/.config/nvim/plugged"
      - "/home/{{ansible_env.SUDO_USER}}/.local/share/nvim/site/autoload"
      - "/home/{{ansible_env.SUDO_USER}}/.ansible/tmp"

  - name: get vim-plug plugin manager
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: "/home/{{ansible_env.SUDO_USER}}/.local/share/nvim/site/autoload/plug.vim"
      mode: '0640'

  - name: installing new init.vim with Plug support - any existing file will be backed up
    template:
      src: templates/init.vim.template
      dest: "/home/{{ ansible_env.SUDO_USER }}/.config/nvim/init.vim"
      mode: '0640'
      backup: yes
    tags:
    - config
  
  - name: install tidal-vim plugin
    shell: nvim +Silent +VimEnter +PlugInstall +qall

  become: yes
  become_method: su
  become_user: "{{ansible_env.SUDO_USER}}"
  become_flags: '-s /bin/bash'

- name: set up tidal symlink in the PATH
  file:
    src: /home/{{ansible_env.SUDO_USER}}/.local/share/nvim/plugged/vim-tidal/bin/tidal
    dest: /usr/local/bin/tidal
    state: link

- include_role:
    name: "roles/ugens-{{ item }}"
  vars:
    editor: "{{ neovim.editor }}"
  with_items: "{{ sc_ugens }}"
  when: sc_ugens is defined
