---

- name: check if tidalvim is already installed
  stat:
    path: /usr/local/bin/tidal
  register: tidalvim

- block:
  - name: create required neovim and Plug directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "/home/{{ansible_env.SUDO_USER}}/.config/nvim"
      - "/home/{{ansible_env.SUDO_USER}}/.local/share/nvim/site/autoload"

  - name: get vim-plug plugin manager
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: "/home/{{ansible_env.SUDO_USER}}/.local/share/nvim/site/autoload/plug.vim"
      mode: '0640'

  - name: installing new init.vim with Plug support - any existing file will be backed up
    template:
      src: templates/init.vim.template
      dest: "/home/{{ ansible_env.SUDO_USER }}/.config/nvim/init.vim"
      mode: '0640'
      backup: yes
    tags:
    - config
  
  - name: install tidal-vim plugin
    shell: nvim +Silent +VimEnter +PlugInstall +qall

  when: tidalvim.stat.islnk is not defined
  become: yes
  become_method: su
  become_user: "{{ansible_env.SUDO_USER}}"
  become_flags: '-s /bin/bash'

- name: set up tidal symlinks in the PATH
  make:
    chdir: /home/{{ansible_env.SUDO_USER}}/.vim/plugged/vim-tidal/
    target: install
  when: tidalvim.stat.islnk is not defined

- name: Remove tidalvim symlink (uses tmux, we don't need it)
  file:
    path: /usr/local/bin/tidalvim
    state: absent

- debug:
    msg: "/usr/local/bin/tidalvim already exists, doing nothing"
  when: tidalvim.stat.islnk is defined
